# Generated by Django 4.0.1 on 2022-01-14 16:08

import authapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='activation_expires',
            field=models.DateTimeField(default=authapp.models.default_exp_date, verbose_name='expiration date'),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='activation_key',
            field=models.CharField(max_length=50, null=True, verbose_name='activation key'),
        ),
    ]
